# Generated by Django 4.2.3 on 2023-08-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='equipo',
            new_name='equipo_actual',
        ),
    ]
